version: "3.8"
services:
  web:
    build:
      context: . # Current directory (where Dockerfile is located)
      dockerfile: Dockerfile # Specify the Dockerfile
    ports:
      - "3000:80"
    volumes:
      - usepop-data:/usr/share/nginx/html/data # Mount the volume
volumes:
  usepop-data: # Define the volume